# Generated by Django 6.0.2 on 2026-02-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
