# Generated by Django 6.0.2 on 2026-02-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0002_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Name',
            new_name='name',
        ),
    ]
