# Generated by Django 6.0.2 on 2026-02-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0003_rename_area_teacher_area_rename_name_teacher_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='area',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='Name',
        ),
    ]
